server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:33060/quartz?autoReconnect=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:admin123}
    driver-class-name:  com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
  main:
    allow-bean-definition-overriding: true
  application:
    name: quartz
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: myQuartzScheduler
          jobStore:
            dataSource: quartzDataSource
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: QRTZ_
            misfireThreshold: 600000
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 200
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource.quartzDataSource:
            driver: com.mysql.cj.jdbc.Driver
            URL: jdbc:mysql://${MYSQL_HOST:localhost}:33060/quartz?autoReconnect=true
            user: root
            password: admin123
            provider: hikaricp

logging:
level:
org.springframework.web.servlet.DispatcherServlet: TRACE
org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE